//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3620
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Public.WebMvc.App_GlobalResources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [GeneratedCode("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class ReusableLibraryCaptcha {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReusableLibraryCaptcha() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Resources.ReusableLibraryCaptcha", Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you cannot read, click to generate a new one.
        /// </summary>
        internal static string HtmlHelperImgTitle {
            get {
                return ResourceManager.GetString("HtmlHelperImgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The challenge code is invalid..
        /// </summary>
        internal static string ValidationChallengeInvalid {
            get {
                return ResourceManager.GetString("ValidationChallengeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code you typed has expired after {0:N0} seconds..
        /// </summary>
        internal static string ValidationCodeExpired {
            get {
                return ResourceManager.GetString("ValidationCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code you typed has no match..
        /// </summary>
        internal static string ValidationNoMatch {
            get {
                return ResourceManager.GetString("ValidationNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code was typed too quickly. Wait at least {0:N0} seconds..
        /// </summary>
        internal static string ValidationTooQuickly {
            get {
                return ResourceManager.GetString("ValidationTooQuickly", resourceCulture);
            }
        }
    }
}
