//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Public.WebMvc.App_GlobalResources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [GeneratedCode("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class ReusableLibraryWebMvc {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReusableLibraryWebMvc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Resources.ReusableLibraryWebMvc", Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied..
        /// </summary>
        internal static string ErrorHttpAccessDenied {
            get {
                return ResourceManager.GetString("ErrorHttpAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request..
        /// </summary>
        internal static string ErrorHttpBadRequest {
            get {
                return ResourceManager.GetString("ErrorHttpBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found..
        /// </summary>
        internal static string ErrorHttpNotFound {
            get {
                return ResourceManager.GetString("ErrorHttpNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching records were found... Please try again with different search terms..
        /// </summary>
        internal static string ErrorNoRecordsFound {
            get {
                return ResourceManager.GetString("ErrorNoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified error just occured..
        /// </summary>
        internal static string ErrorUnspecified {
            get {
                return ResourceManager.GetString("ErrorUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string NextNPages {
            get {
                return ResourceManager.GetString("NextNPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next {0} Pages.
        /// </summary>
        internal static string NextNPagesTitle {
            get {
                return ResourceManager.GetString("NextNPagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        internal static string NextPageTitle {
            get {
                return ResourceManager.GetString("NextPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string PreviousNPages {
            get {
                return ResourceManager.GetString("PreviousNPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous {0} Pages.
        /// </summary>
        internal static string PreviousNPagesTitle {
            get {
                return ResourceManager.GetString("PreviousNPagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        internal static string PreviousPageTitle {
            get {
                return ResourceManager.GetString("PreviousPageTitle", resourceCulture);
            }
        }
    }
}
